stages:
  - compile
  - publish
 
compile_pdf:
  stage: compile
  script: 
    - bash ./download_latex_script.sh
    - ./latexdockercmd.sh pdflatex cv.tex
  artifacts:
    paths:
      - cv.pdf

deploy_on_web:
  stage: publish
  script:
    - ls
  only:
    - master
