name: "Build PDF"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/moderncv/debian-texlive-docker:main
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build PDF
        run: latexmk
      - name: Upload cv
        uses: actions/upload-artifact@v4
        with:
          name: cv.pdf
          path: ./cv.pdf
      - name: Upload resume
        uses: actions/upload-artifact@v4
        with:
          name: resume.pdf
          path: ./resume.pdf
